package Student_Management_System;

import java.awt.BorderLayout;
import java.awt.EventQueue;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import javax.swing.JScrollPane;
import javax.swing.JScrollBar;
import javax.swing.JTable;
import javax.swing.JLabel;
import javax.swing.JEditorPane;

public class TestHtml extends JFrame {

	private JPanel contentPane;

	/**
	 * Launch the application.
	 */
	public static void main(String[] args) {
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					TestHtml frame = new TestHtml();
					frame.setVisible(true);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
	}

	/**
	 * Create the frame.
	 */
	public TestHtml() {
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setBounds(100, 100, 1080, 577);
		contentPane = new JPanel();
		contentPane.setBorder(new EmptyBorder(5, 5, 5, 5));
		setContentPane(contentPane);
		contentPane.setLayout(null);
		
		JEditorPane html_page = new JEditorPane();
		html_page.setBounds(0, 0, 1064, 538);
		contentPane.add(html_page);
		
		html_page.setContentType("text/html");
		html_page.setText("<!DOCTYPE html>\r\n"
				+ "<html lang=\"en\">\r\n"
				+ "  <head>\r\n"
				+ "    <meta charset=\"UTF-8\" />\r\n"
				+ "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n"
				+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n"
				+ "    <title>Document</title>\r\n"
				+ "    <link\r\n"
				+ "      href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\"\r\n"
				+ "      rel=\"stylesheet\"\r\n"
				+ "      integrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\"\r\n"
				+ "      crossorigin=\"anonymous\"\r\n"
				+ "    />\r\n"
				+ "    <link rel=\"stylesheet\" href=\"style.css\" />\r\n"
				+ "  </head>\r\n"
				+ "  <body>\r\n"
				+ "    <!-- Navbar -->\r\n"
				+ "    <div class=\"container\">\r\n"
				+ "      <nav class=\"navbar navbar-expand-lg navbar-light bg-light\">\r\n"
				+ "        <div class=\"container-fluid\">\r\n"
				+ "          <a class=\"navbar-brand\" href=\"#\">\r\n"
				+ "            <img src=\"resource/logo.png\" alt=\"panda logo\" id=\"panda_logo\" />\r\n"
				+ "          </a>\r\n"
				+ "          <button\r\n"
				+ "            class=\"navbar-toggler\"\r\n"
				+ "            type=\"button\"\r\n"
				+ "            data-bs-toggle=\"collapse\"\r\n"
				+ "            data-bs-target=\"#navbarNav\"\r\n"
				+ "            aria-controls=\"navbarNav\"\r\n"
				+ "            aria-expanded=\"false\"\r\n"
				+ "            aria-label=\"Toggle navigation\"\r\n"
				+ "          >\r\n"
				+ "            <span class=\"navbar-toggler-icon\"></span>\r\n"
				+ "          </button>\r\n"
				+ "          <div class=\"collapse navbar-collapse\" id=\"navbarNav\">\r\n"
				+ "            <ul class=\"navbar-nav\">\r\n"
				+ "              <li class=\"nav-item\">\r\n"
				+ "                <a class=\"nav-link active\" aria-current=\"page\" href=\"#Home\"\r\n"
				+ "                  >Home</a\r\n"
				+ "                >\r\n"
				+ "              </li>\r\n"
				+ "              <li class=\"nav-item\">\r\n"
				+ "                <a class=\"nav-link\" href=\"#Shoes\">Shoes</a>\r\n"
				+ "              </li>\r\n"
				+ "              <li class=\"nav-item\">\r\n"
				+ "                <a class=\"nav-link\" href=\"#Backpacks\">Backpacks</a>\r\n"
				+ "              </li>\r\n"
				+ "              <li class=\"nav-item\">\r\n"
				+ "                <a class=\"nav-link\" href=\"#Contacts\">Contact</a>\r\n"
				+ "              </li>\r\n"
				+ "            </ul>\r\n"
				+ "          </div>\r\n"
				+ "        </div>\r\n"
				+ "      </nav>\r\n"
				+ "    </div>\r\n"
				+ "\r\n"
				+ "    <!-- Carousel -->\r\n"
				+ "    <div id=\"Home\" class=\"container\">\r\n"
				+ "      <div\r\n"
				+ "        id=\"carouselExampleControls\"\r\n"
				+ "        class=\"carousel slide\"\r\n"
				+ "        data-bs-ride=\"carousel\"\r\n"
				+ "      >\r\n"
				+ "        <div class=\"carousel-inner orange-bg\">\r\n"
				+ "          <div class=\"carousel-item active\">\r\n"
				+ "            <div class=\"row align-items-center\">\r\n"
				+ "              <div class=\"col-md-7\">\r\n"
				+ "                <h1>Mega LCD Tv for Sports</h1>\r\n"
				+ "                <p>This is the best tv to watch movies in 3D</p>\r\n"
				+ "                <h1>$1200</h1>\r\n"
				+ "                <button class=\"btn buy-now\">Buy Now</button>\r\n"
				+ "              </div>\r\n"
				+ "              <div class=\"col-md-5\">\r\n"
				+ "                <img\r\n"
				+ "                  src=\"resource/banner-images/tv.png\"\r\n"
				+ "                  alt=\"TV Banner\"\r\n"
				+ "                  class=\"d-block w-100\"\r\n"
				+ "                />\r\n"
				+ "              </div>\r\n"
				+ "            </div>\r\n"
				+ "          </div>\r\n"
				+ "          <div class=\"carousel-item\">\r\n"
				+ "            <div class=\"row align-items-center\">\r\n"
				+ "              <div class=\"col-md-7\">\r\n"
				+ "                <h1>Cool HeadPhones</h1>\r\n"
				+ "                <p>Best sound quality for gaming Experience</p>\r\n"
				+ "                <h1>$800</h1>\r\n"
				+ "                <button class=\"btn buy-now\">Buy Now</button>\r\n"
				+ "              </div>\r\n"
				+ "              <div class=\"col-md-5\">\r\n"
				+ "                <img\r\n"
				+ "                  src=\"resource/banner-images/headphone.png\"\r\n"
				+ "                  class=\"d-block w-100\"\r\n"
				+ "                  alt=\"Headphone Banner\"\r\n"
				+ "                />\r\n"
				+ "              </div>\r\n"
				+ "            </div>\r\n"
				+ "          </div>\r\n"
				+ "          <div class=\"carousel-item\">\r\n"
				+ "            <div class=\"row align-items-center\">\r\n"
				+ "              <div class=\"col-md-7\">\r\n"
				+ "                <h1>X-Box for your living room</h1>\r\n"
				+ "                <p>Get your desired gaming Experience</p>\r\n"
				+ "                <h1>$5000</h1>\r\n"
				+ "                <button class=\"btn buy-now\">Buy Now</button>\r\n"
				+ "              </div>\r\n"
				+ "              <div class=\"col-md-5\">\r\n"
				+ "                <img\r\n"
				+ "                  src=\"resource/banner-images/xbox.png\"\r\n"
				+ "                  class=\"d-block w-100\"\r\n"
				+ "                  alt=\"X-Box banner\"\r\n"
				+ "                />\r\n"
				+ "              </div>\r\n"
				+ "            </div>\r\n"
				+ "          </div>\r\n"
				+ "        </div>\r\n"
				+ "        <button\r\n"
				+ "          class=\"carousel-control-prev\"\r\n"
				+ "          type=\"button\"\r\n"
				+ "          data-bs-target=\"#carouselExampleControls\"\r\n"
				+ "          data-bs-slide=\"prev\"\r\n"
				+ "        >\r\n"
				+ "          <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n"
				+ "          <span class=\"visually-hidden\">Previous</span>\r\n"
				+ "        </button>\r\n"
				+ "        <button\r\n"
				+ "          class=\"carousel-control-next\"\r\n"
				+ "          type=\"button\"\r\n"
				+ "          data-bs-target=\"#carouselExampleControls\"\r\n"
				+ "          data-bs-slide=\"next\"\r\n"
				+ "        >\r\n"
				+ "          <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n"
				+ "          <span class=\"visually-hidden\">Next</span>\r\n"
				+ "        </button>\r\n"
				+ "      </div>\r\n"
				+ "    </div>\r\n"
				+ "\r\n"
				+ "    <div class=\"container categories\">\r\n"
				+ "      <div class=\"row\">\r\n"
				+ "        <div class=\"col-md-4\">\r\n"
				+ "          <div\r\n"
				+ "            class=\"\r\n"
				+ "              categories1\r\n"
				+ "              d-flex\r\n"
				+ "              justify-content-between\r\n"
				+ "              align-items-center\r\n"
				+ "            \"\r\n"
				+ "          >\r\n"
				+ "            <h1>Watch</h1>\r\n"
				+ "            <img src=\"resource/categories/watch.png\" alt=\"watch\" />\r\n"
				+ "          </div>\r\n"
				+ "        </div>\r\n"
				+ "        <div class=\"col-md-4\">\r\n"
				+ "          <div\r\n"
				+ "            class=\"\r\n"
				+ "              categories2\r\n"
				+ "              d-flex\r\n"
				+ "              justify-content-between\r\n"
				+ "              align-items-center\r\n"
				+ "            \"\r\n"
				+ "          >\r\n"
				+ "            <h1>Bag</h1>\r\n"
				+ "            <img src=\"resource/categories/bag.png\" alt=\"bag\" />\r\n"
				+ "          </div>\r\n"
				+ "        </div>\r\n"
				+ "        <div class=\"col-md-4\">\r\n"
				+ "          <div\r\n"
				+ "            class=\"\r\n"
				+ "              categories3\r\n"
				+ "              d-flex\r\n"
				+ "              justify-content-between\r\n"
				+ "              align-items-center\r\n"
				+ "            \"\r\n"
				+ "          >\r\n"
				+ "            <h1>Shoes</h1>\r\n"
				+ "            <img src=\"resource/categories/shoes.png\" alt=\"shoe\" />\r\n"
				+ "          </div>\r\n"
				+ "        </div>\r\n"
				+ "      </div>\r\n"
				+ "    </div>\r\n"
				+ "\r\n"
				+ "    <!-- Card -->\r\n"
				+ "    <div class=\"container shoes\" id=\"Shoes\">\r\n"
				+ "      <h1>Shoes</h1>\r\n"
				+ "      <div class=\"row row-cols-1 row-cols-md-3 g-4\">\r\n"
				+ "        <div class=\"col\">\r\n"
				+ "          <div class=\"card h-100\">\r\n"
				+ "            <img\r\n"
				+ "              src=\"resource/shoes/shoe-1.png\"\r\n"
				+ "              class=\"card-img-top\"\r\n"
				+ "              alt=\"Shoe1\"\r\n"
				+ "            />\r\n"
				+ "            <div class=\"card-body\">\r\n"
				+ "              <h5 class=\"card-title\">Supple 350</h5>\r\n"
				+ "              <p class=\"card-text\">\r\n"
				+ "                This is a wider card with supporting text below as a natural\r\n"
				+ "                lead-in to additional content. This content is a little bit\r\n"
				+ "                longer.\r\n"
				+ "              </p>\r\n"
				+ "              <h5>$120</h5>\r\n"
				+ "              <button class=\"btn buy-now\">Buy Now</button>\r\n"
				+ "            </div>\r\n"
				+ "          </div>\r\n"
				+ "        </div>\r\n"
				+ "        <div class=\"col\">\r\n"
				+ "          <div class=\"card h-100\">\r\n"
				+ "            <img\r\n"
				+ "              src=\"resource/shoes/shoe-2.png\"\r\n"
				+ "              class=\"card-img-top\"\r\n"
				+ "              alt=\"Shoe2\"\r\n"
				+ "            />\r\n"
				+ "            <div class=\"card-body\">\r\n"
				+ "              <h5 class=\"card-title\">Nike 320</h5>\r\n"
				+ "              <p class=\"card-text\">\r\n"
				+ "                This is a wider card with supporting text below as a natural\r\n"
				+ "                lead-in to additional content. This content is a little bit\r\n"
				+ "                longer.\r\n"
				+ "              </p>\r\n"
				+ "              <h5>$320</h5>\r\n"
				+ "              <button class=\"btn buy-now\">Buy Now</button>\r\n"
				+ "            </div>\r\n"
				+ "          </div>\r\n"
				+ "        </div>\r\n"
				+ "        <div class=\"col\">\r\n"
				+ "          <div class=\"card h-100\">\r\n"
				+ "            <img\r\n"
				+ "              src=\"resource/shoes/shoe-3.png\"\r\n"
				+ "              class=\"card-img-top\"\r\n"
				+ "              alt=\"Shoe3\"\r\n"
				+ "            />\r\n"
				+ "            <div class=\"card-body\">\r\n"
				+ "              <h5 class=\"card-title\">Red Max</h5>\r\n"
				+ "              <p class=\"card-text\">\r\n"
				+ "                This is a wider card with supporting text below as a natural\r\n"
				+ "                lead-in to additional content. This content is a little bit\r\n"
				+ "                longer.\r\n"
				+ "              </p>\r\n"
				+ "              <h5>$350</h5>\r\n"
				+ "              <button class=\"btn buy-now\">Buy Now</button>\r\n"
				+ "            </div>\r\n"
				+ "          </div>\r\n"
				+ "        </div>\r\n"
				+ "      </div>\r\n"
				+ "    </div>\r\n"
				+ "\r\n"
				+ "    <!-- BagPacks -->\r\n"
				+ "    <div class=\"container bagpacks\" id=\"Backpacks\">\r\n"
				+ "      <h1>BagPacks</h1>\r\n"
				+ "      <div class=\"row row-cols-1 row-cols-md-3 g-4\">\r\n"
				+ "        <div class=\"col\">\r\n"
				+ "          <div class=\"card h-100\">\r\n"
				+ "            <img\r\n"
				+ "              src=\"resource/bags/bag-1.png\"\r\n"
				+ "              class=\"card-img-top\"\r\n"
				+ "              alt=\"bag1\"\r\n"
				+ "            />\r\n"
				+ "            <div class=\"card-body\">\r\n"
				+ "              <h5 class=\"card-title\">Red Bag</h5>\r\n"
				+ "              <p class=\"card-text\">\r\n"
				+ "                This is a wider card with supporting text below as a natural\r\n"
				+ "                lead-in to additional content. This content is a little bit\r\n"
				+ "                longer.\r\n"
				+ "              </p>\r\n"
				+ "              <h5>$120</h5>\r\n"
				+ "            </div>\r\n"
				+ "            <div class=\"card-footer\">\r\n"
				+ "              <button class=\"btn buy-now\">Buy Now</button>\r\n"
				+ "            </div>\r\n"
				+ "          </div>\r\n"
				+ "        </div>\r\n"
				+ "        <div class=\"col\">\r\n"
				+ "          <div class=\"card h-100\">\r\n"
				+ "            <img\r\n"
				+ "              src=\"resource/bags/bag-2.png\"\r\n"
				+ "              class=\"card-img-top\"\r\n"
				+ "              alt=\"bag2\"\r\n"
				+ "            />\r\n"
				+ "            <div class=\"card-body\">\r\n"
				+ "              <h5 class=\"card-title\">Blue Bag</h5>\r\n"
				+ "              <p class=\"card-text\">\r\n"
				+ "                This is a wider card with supporting text below as a natural\r\n"
				+ "                lead-in to additional content. This content is a little bit\r\n"
				+ "                longer.\r\n"
				+ "              </p>\r\n"
				+ "              <h5>$320</h5>\r\n"
				+ "            </div>\r\n"
				+ "            <div class=\"card-footer\">\r\n"
				+ "              <button class=\"btn buy-now\">Buy Now</button>\r\n"
				+ "            </div>\r\n"
				+ "          </div>\r\n"
				+ "        </div>\r\n"
				+ "        <div class=\"col\">\r\n"
				+ "          <div class=\"card h-100\">\r\n"
				+ "            <img\r\n"
				+ "              src=\"resource/bags/bag-3.png\"\r\n"
				+ "              class=\"card-img-top\"\r\n"
				+ "              alt=\"bag3\"\r\n"
				+ "            />\r\n"
				+ "            <div class=\"card-body\">\r\n"
				+ "              <h5 class=\"card-title\">Black Bag</h5>\r\n"
				+ "              <p class=\"card-text\">\r\n"
				+ "                This is a wider card with supporting text below as a natural\r\n"
				+ "                lead-in to additional content. This content is a little bit\r\n"
				+ "                longer.\r\n"
				+ "              </p>\r\n"
				+ "              <h5>$200</h5>\r\n"
				+ "            </div>\r\n"
				+ "            <div class=\"card-footer\">\r\n"
				+ "              <button class=\"btn buy-now\">Buy Now</button>\r\n"
				+ "            </div>\r\n"
				+ "          </div>\r\n"
				+ "        </div>\r\n"
				+ "      </div>\r\n"
				+ "    </div>\r\n"
				+ "\r\n"
				+ "    <div\r\n"
				+ "      class=\"\r\n"
				+ "        container\r\n"
				+ "        orange-bg\r\n"
				+ "        d-flex\r\n"
				+ "        justify-content-center\r\n"
				+ "        align-items-center\r\n"
				+ "      \"\r\n"
				+ "      id=\"subscribe\"\r\n"
				+ "    >\r\n"
				+ "      <div id=\"Contacts\">\r\n"
				+ "        <h3>LET'S STAY IN TOUCH</h3>\r\n"
				+ "        <h6>Get updates on sales, specials and more</h6>\r\n"
				+ "        <input class=\"form-control\" type=\"text\" />\r\n"
				+ "        <button class=\"btn buy-now\">Submit</button>\r\n"
				+ "      </div>\r\n"
				+ "    </div>\r\n"
				+ "\r\n"
				+ "    <footer>\r\n"
				+ "      <small>&copyPanda E-commerce. All rights reserved by Moheb</small>\r\n"
				+ "    </footer>\r\n"
				+ "\r\n"
				+ "    <!-- JavaScript Bundle with Popper -->\r\n"
				+ "    <script\r\n"
				+ "      src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\"\r\n"
				+ "      integrity=\"sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM\"\r\n"
				+ "      crossorigin=\"anonymous\"\r\n"
				+ "    ></script>\r\n"
				+ "  </body>\r\n"
				+ "</html>\r\n"
				+ "");
	}
}
